"""Shared renderer constants."""

from __future__ import annotations

DOOR_VISUAL_ASPECT = 1.0 / 3.0
THIN_PANEL_RENDER_OFFSET = 0.06
THIN_PANEL_NEAR_CLIP = 0.01
THIN_PANEL_OCCLUSION_SLACK = 0.45
DEFAULT_OCCLUSION_SLACK = 0.04
WALL_PANEL_OBJECT_IDS = {"blackboard", "elevator", "exit_panel"}
TOP_FACE_NEAR_CLIP = 0.24
SMALL_OBJECT_TOP_HIDE_DISTANCE = 0.85
SMALL_OBJECT_TOP_MAX_HEIGHT = 0.35
OBJECT_STABLE_VERTICAL_DISTANCE = 1.15
WORLD_PANEL_MIN_VERTICAL_DISTANCE = 0.42
