"""Global settings for LabMidnight."""

from __future__ import annotations

import math


TITLE = "LabMidnight（加班累了是吗）"
SCREEN_WIDTH = 960
SCREEN_HEIGHT = 540
HALF_WIDTH = SCREEN_WIDTH // 2
HALF_HEIGHT = SCREEN_HEIGHT // 2
FPS = 60
BUILDING_BOTTOM_FLOOR = 1
BUILDING_TOP_FLOOR = 4

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = 480
MAX_DEPTH = 20.0
DELTA_ANGLE = FOV / NUM_RAYS
DISTANCE_TO_PROJECTION = (SCREEN_WIDTH / 2) / math.tan(FOV / 2)
VERTICAL_PROJECTION = DISTANCE_TO_PROJECTION
SCALE = max(1, SCREEN_WIDTH // NUM_RAYS)

TILE_SIZE_CM = 60
CAMERA_HEIGHT_CM = 175
CEILING_HEIGHT_TILES = 5.0
CEILING_HEIGHT_CM = int(TILE_SIZE_CM * CEILING_HEIGHT_TILES)
VERTICAL_UNITS_PER_TILE = 1.0
CEILING_HEIGHT_UNITS = CEILING_HEIGHT_TILES * VERTICAL_UNITS_PER_TILE
CAMERA_HEIGHT_UNITS = (CAMERA_HEIGHT_CM / TILE_SIZE_CM) * VERTICAL_UNITS_PER_TILE
CEILING_TEXTURE_TILE_SPAN = 3.0

PLAYER_RADIUS = 0.34
OBJECT_COLLISION_RADIUS = 0.55
DOOR_COLLISION_THICKNESS = 0.10
DOOR_OPEN_SPEED = 2.0
DOOR_PASSABLE_PROGRESS = 0.72
DOOR_OPEN_REST_WIDTH = 0.18
PLAYER_SPEED = 3.0
PLAYER_ROTATION_SPEED = 2.45
MOUSE_SENSITIVITY = 0.0032
MOUSE_PITCH_SENSITIVITY = 1.35
INTERACT_DISTANCE = 1.65
RAY_NEAR_CLIP = 0.18
DOOR_PANEL_NEAR_CLIP = 0.08
PITCH_VISUAL_RANGE = 520

FLASHLIGHT_MAX = 100.0
FLASHLIGHT_START = 86.0
FLASHLIGHT_DRAIN_PER_SEC = 2.2
BATTERY_RESTORE = 35.0
SANITY_MAX = 100.0
SANITY_DARK_DRAIN_PER_SEC = 1.2
SANITY_LOW_AUDIO_THRESHOLD = 40

STATE_MENU = "menu"
STATE_PLAYING = "playing"
STATE_PAUSED = "paused"
STATE_INVENTORY = "inventory"
STATE_FLOOR_CONFIRM = "floor_confirm"
STATE_SUCCESS = "success"
STATE_FAILURE = "failure"

TILE_EMPTY = 0
TILE_WALL = 1
TILE_GUARD_DOOR = 2
TILE_LAB_DOOR = 3
TILE_CLASSROOM_DOOR = 4
TILE_POWER_DOOR = 5
TILE_EXIT_DOOR = 6
TILE_EVENT = 7

DOOR_TILES = {
    TILE_GUARD_DOOR,
    TILE_LAB_DOOR,
    TILE_CLASSROOM_DOOR,
    TILE_POWER_DOOR,
    TILE_EXIT_DOOR,
}

WALL_COLORS = {
    TILE_WALL: (75, 83, 92),
    TILE_GUARD_DOOR: (95, 72, 53),
    TILE_LAB_DOOR: (104, 77, 56),
    TILE_CLASSROOM_DOOR: (70, 98, 96),
    TILE_POWER_DOOR: (105, 93, 49),
    TILE_EXIT_DOOR: (114, 54, 48),
}

COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (235, 238, 230)
COLOR_TEXT = (222, 230, 220)
COLOR_MUTED = (144, 154, 146)
COLOR_WARNING = (230, 189, 92)
COLOR_DANGER = (225, 93, 81)
COLOR_PANEL = (10, 14, 15)
COLOR_PANEL_EDGE = (70, 83, 80)
